// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kravcvspqyrvnlsfoouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYXZjdnNwcXlydm5sc2Zvb3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDQyOTAsImV4cCI6MjA2NDYyMDI5MH0.f9APkhuE4RNCsRH32gnytbbzHa8VJvdgTYWJQnVTLxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);